In [15]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [2]:
# Series itu kek 'dict-like' pandas data structure

obj = pd.Series([4,7,-5,3])
# A Series is a one-dimensional array-like object containing a sequence of values (of
# similar types to NumPy types) and an associated array of data labels, called its index

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
#The string representation of a Series displayed interactively shows the index on the
#left and the values on the right.
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# create a Series with an index identifying each data point
# with a label:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
# you can use labels in the index when selecting single
# values or a set of values:
obj2['a']

-5

In [10]:
obj2['d']

4

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [12]:
# Using NumPy functions or NumPy-like operations, such as filtering with a boolean
# array, scalar multiplication, or applying math functions, will preserve the index-value link
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
# Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values. 
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
# create a Series from it by passing the dict:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

# Lu bisa bikin Series dari Dict/Konversi

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
# When you are only passing a dict, the index in the resulting Series will have the dict’s
# keys in sorted order
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4
# since no value for 'California' was found, it appears as NaN (not a number)
# Since 'Utah' was not included in states, it is excluded from the resulting object.

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)
# isnull and notnull functions in pandas should be used to detect missing data
# isnull untuk memeriksa apakah ada valuenya apa nggak

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)
# notnull untuk memeriksa apakah NGGAK ada valuenya apa iya

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
# A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations
obj3 + obj4
# Kalo langsung ditambah, di salah satu yg gaada valuenya jadi NaN

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
# Series bisa punya namanya sendiri, yang dapat diassign dengan method .name
obj4.name = 'population'

In [32]:
# method name dari index itu bisa diassign juga
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
# Series’s index can be altered in-place by assignment
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
# DataFrame itu adalah tabel kotak dari data dan mengandung kumpulan kolom, yang masing2nya bisa punya jenis nilai berbeda (numeric, string, boolean, etc)
# DataFrame ini punya indeks kolom dan baris, jadi bisa disebut dict Series yg punya indeks yg sama
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
# One of the most common to construct DataFrame is from a dict of equal-length lists or NumPy arrays

In [38]:
frame
# the resulting DataFrame will have its index assigned automatically, and the columns are placed in sorted order

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()
# for large DataFrame, the head method selects only the first five rows

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
# Jika dispesifikasiin sekuen kolomnya, urutan kolomnya bakal seperti itu
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four',
                           'five', 'six'])
# Missing values akan ada jika diassign kolom yg gaada valuenya

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
# Kolom DataFrame dapat diambil as a Series dg notasi 'dict-like' atau dg attribute
frame2['state']
# dengan notasi dict-like

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [47]:
frame.year
# dengan notasi attribute

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [48]:
# Bukan cuma kalom, baris juga bisa diretrieve dengan menyebutkan label baris di method .loc
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
# Columns can be modified by assignment
frame2['debt'] = 16.5

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [51]:
frame2['debt'] = np.arange(6.)

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [53]:
# When you are assigning lists or arrays to a column, the value’s length must match the
# length of the DataFrame. If you assign a Series, its labels will be realigned exactly to
# the DataFrame’s index
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [54]:
# Kolom dapat diganti nilainya dengan assignment
frame['debt'] = val

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [56]:
# Assigning a column that doesn’t exist will create a new column. The del keyword will
# delete columns as with a dict.
frame2['eastern'] = frame2.state == 'Ohio'

In [57]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False

In [58]:
#  del method can then be used to remove this column
del frame2['eastern']

In [59]:
frame.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

In [61]:
# Another common form of data is a nested dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [62]:
# If the nested dict is passed to the DataFrame, pandas will interpret 
# the outer dict keys as the columns and the inner keys as the row indices
frame3 = pd.DataFrame(pop)

In [63]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [64]:
# You can transpose the DataFrame (swap rows and columns) with similar syntax to a
# NumPy array
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [65]:
# The keys in the inner dicts are combined and sorted to form the index in the result.
# Kalo nggak dispecified, keys di inner dict bakal dikombinasiin dan disortir di DataFrame
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [66]:
# Dicts of Series are treated in much the same way
# Kalo nggak dispecified, keys di inner dict bakal dikombinasiin dan disortir di Dict of Series juga
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [67]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [68]:
# Lu bisa ngeassign column dan rows na
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [69]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [70]:
# As with Series, the values attribute returns the data contained in the DataFrame as a
# two-dimensional ndarray
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [71]:
# If the DataFrame’s columns are different dtypes, the dtype of the values array will be
# chosen to accommodate all of the columns
frame2.values

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.0],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0],
       [2003, 'Nevada', 3.2, 5.0]], dtype=object)

In [72]:
# Index Objects

obj = pd.Series(range(3), index=['a', 'b', 'c'])
# Objek indeks di Pandas itu indeks dari series atau DataFrame

In [73]:
index = obj.index

In [74]:
index

Index(['a', 'b', 'c'], dtype='object')

In [75]:
index[1:]
# Bisa diretrieve

Index(['b', 'c'], dtype='object')

In [76]:
index[1] = 'd'
# Tapi gabisa diubah

TypeError: Index does not support mutable operations

In [77]:
labels = pd.Index(np.arange(3))

In [78]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [79]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
# Bisa distate separately dari valuenya

In [80]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [81]:
obj2.index is labels

True

In [82]:
# Index itu mirip kek array, sama fixed-size set
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [83]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [84]:
'Ohio' in frame3.columns

True

In [85]:
2003 in frame3.index

False

In [86]:
# pandas Index dapat punya label duplikat
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [87]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [88]:
index.append(['Foo'])

TypeError: all inputs must be Index

In [89]:
# Reindexing

# Reindexing is to create a new object with the data conformed to a new index
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [90]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [91]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [92]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [93]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [94]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [95]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [96]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [97]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [98]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [99]:
states = ['Texas', 'Utah', 'California']

In [100]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [101]:
frame.loc[['a', 'b', 'c', 'd'], states]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [102]:
# Dropping Entries from an Axis (axis row (0) atau column (1)

obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [103]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [104]:
new_obj = obj.drop('c')

# drop method bakal ngembaliin objek baru dengan value yang belum dihapus dari axis

In [105]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [106]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [107]:
# Pada DataFrame, index dapat dihapus dari axis

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [108]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [109]:
# drop method with a sequence of labels will drop values from the row labels (axis 0)

data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
# Kamu juga bisa ngehapus suatu kolom atau baris dengan menspesifikasikan axisnya, dengan stating 0 atau 1, atau columns/rows

data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [111]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [112]:
obj.drop('c', inplace=True)

# Hati-hati dengan inplace, karena bakal hapus data yg didrop

In [113]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [114]:
# Indexing, Selection, and Filtering

obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [115]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj['b']

1.0

In [117]:
obj[1]

1.0

In [118]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [119]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [120]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [121]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [122]:
# SLicing with labels is end-point inclusive

obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [123]:
obj['b':'c'] = 5

In [124]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [126]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [127]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [130]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [131]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [132]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [133]:
data > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [134]:
data[data < 5] = 0

In [135]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
# Selection with loc and iloc

# loc and iloc -> select a subset of rows and columns from a DataFrame =

# loc -> using axis labels
# iloc -> using integers (rows or columns index)

data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [137]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [138]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [139]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [140]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [142]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
# Integer Indexes

In [143]:
ser = pd.Series(np.arange(3.))

In [146]:
ser[1]

1.0

In [147]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [148]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [149]:
ser2[-1]

2.0

In [152]:
ser[:1]

0    0.0
dtype: float64

In [153]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [154]:
ser.iloc[:1]

0    0.0
dtype: float64

In [156]:
# Arithmetic and Data Alignment

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [158]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [159]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [160]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [161]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [163]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

In [164]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [165]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [166]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [167]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [168]:
df1 = pd.DataFrame({'A': [1,2]})

In [169]:
df2 = pd.DataFrame({'B': [3,4]})

In [170]:
df1

A
0  1
1  2

In [171]:
df2

B
0  3
1  4

In [172]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [173]:
# Arithmetic methods with fill values

df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))

In [174]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))

In [175]:
df2.loc[1, 'b'] = np.nan

In [176]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [177]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [178]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [180]:
df1.add(df2, fill_value=0)

# fill_value will fill the NaN or Null value with whatever number that it assign to

a     b     c     d     e
0   0.0   2.0   4.0   6.0   5.0
1   9.0   6.0  13.0  15.0  10.0
2  18.0  20.0  22.0  24.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [181]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [182]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [183]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [186]:
df1.radd(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [187]:
df1.sub(df2, fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0

In [188]:
df1.rsub(df2, fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0  -5.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [189]:
df1.div(df2, fill_value=1)

a         b         c         d         e
0       NaN  1.000000  1.000000  1.000000  0.250000
1  0.800000  5.000000  0.857143  0.875000  0.111111
2  0.800000  0.818182  0.833333  0.846154  0.071429
3  0.066667  0.062500  0.058824  0.055556  0.052632

In [190]:
df1.rdiv(df2, fill_value=1)

a          b          c          d     e
0    NaN   1.000000   1.000000   1.000000   4.0
1   1.25   0.200000   1.166667   1.142857   9.0
2   1.25   1.222222   1.200000   1.181818  14.0
3  15.00  16.000000  17.000000  18.000000  19.0

In [191]:
df1.floordiv(df2, fill_value=1)

a    b    c    d    e
0  NaN  1.0  1.0  1.0  0.0
1  0.0  5.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0

In [192]:
df1.rfloordiv(df2, fill_value=1)

a     b     c     d     e
0   NaN   1.0   1.0   1.0   4.0
1   1.0   0.0   1.0   1.0   9.0
2   1.0   1.0   1.0   1.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [193]:
df1.mul(df2, fill_value=1)

a     b      c      d     e
0   0.0   1.0    4.0    9.0   4.0
1  20.0   5.0   42.0   56.0   9.0
2  80.0  99.0  120.0  143.0  14.0
3  15.0  16.0   17.0   18.0  19.0

In [194]:
df1.rmul(df2, fill_value=1)

a     b      c      d     e
0   0.0   1.0    4.0    9.0   4.0
1  20.0   5.0   42.0   56.0   9.0
2  80.0  99.0  120.0  143.0  14.0
3  15.0  16.0   17.0   18.0  19.0

In [195]:
df1.pow(df2, fill_value=1)

a             b             c             d    e
0  1.000000e+00  1.000000e+00  4.000000e+00  2.700000e+01  1.0
1  1.024000e+03  5.000000e+00  2.799360e+05  5.764801e+06  1.0
2  1.073742e+09  3.138106e+10  1.000000e+12  3.452271e+13  1.0
3  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.0

In [196]:
df1.rpow(df2, fill_value=1)

a             b             c             d     e
0          1.0  1.000000e+00  4.000000e+00  2.700000e+01   4.0
1        625.0  1.000000e+00  1.176490e+05  2.097152e+06   9.0
2  100000000.0  2.357948e+09  6.191736e+10  1.792160e+12  14.0
3         15.0  1.600000e+01  1.700000e+01  1.800000e+01  19.0

In [198]:
# Operations between DataFrame and Series

arr = np.arange(12.).reshape((3,4))

In [199]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [200]:
arr[0]

array([0., 1., 2., 3.])

In [201]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [217]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [218]:
series = frame.iloc[0]

In [219]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [220]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [221]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [224]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [225]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [226]:
series3 = frame['d']

In [227]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [228]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [229]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [230]:
# Function Application and Mapping

frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [231]:
frame

b         d         e
Utah   -0.496990 -0.844033 -0.970313
Ohio   -0.157969  1.369574 -0.361820
Texas   0.661614 -0.216340  1.631480
Oregon -0.202642  0.473624 -2.644110

In [232]:
np.abs(frame)

b         d         e
Utah    0.496990  0.844033  0.970313
Ohio    0.157969  1.369574  0.361820
Texas   0.661614  0.216340  1.631480
Oregon  0.202642  0.473624  2.644110

In [234]:
f = lambda x: x.max() - x.min()

In [235]:
frame.apply(f)

b    1.158604
d    2.213607
e    4.275590
dtype: float64

In [236]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [237]:
frame.apply(f)

b         d        e
min -0.496990 -0.844033 -2.64411
max  0.661614  1.369574  1.63148

In [238]:
format = lambda x: '%.2f' % x

In [239]:
frame.applymap(format)

b      d      e
Utah    -0.50  -0.84  -0.97
Ohio    -0.16   1.37  -0.36
Texas    0.66  -0.22   1.63
Oregon  -0.20   0.47  -2.64

In [240]:
frame['e'].map(format)

Utah      -0.97
Ohio      -0.36
Texas      1.63
Oregon    -2.64
Name: e, dtype: object

In [241]:
# Sorting and Ranking

obj = pd. Series(range(4), index=['d', 'a', 'b', 'c'])

In [242]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [243]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [244]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [245]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [246]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [247]:
obj = pd.Series([4,7,-3,2])

In [248]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [249]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [250]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [251]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [252]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [253]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [254]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [255]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [256]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [257]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [258]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [259]:
# Assign tie values the maximum rank in the group

obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [261]:
frame = pd.DataFrame({'b': [4.3,7,-3,2], 'a': [0,1,0,1], 'c': [-2,5,8,-2.5]})

In [262]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [263]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [265]:
# Axis Indexes with Duplicate Labels

obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [266]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [267]:
obj.index.is_unique

False

In [268]:
obj['a']

a    0
a    1
dtype: int64

In [269]:
obj['c']

4

In [270]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [271]:
df

0         1         2
a -0.108198  1.049998 -1.432150
a -0.843409  0.898796  0.498318
b  0.584612  0.539161 -0.237065
b -0.602454 -1.146837  0.631399

In [272]:
df.loc['b']

0         1         2
b  0.584612  0.539161 -0.237065
b -0.602454 -1.146837  0.631399

In [274]:
# Summarizing and Computing Descriptive Statistics

df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [275]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [276]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [277]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [278]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [279]:
df.idxmax()

one    b
two    d
dtype: object

In [280]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [281]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [282]:
obj = pd.Series(['a','a','b','b','c'] * 4)

In [283]:
obj.describe()

count     20
unique     3
top        a
freq       8
dtype: object

In [286]:
import pandas_datareader.data as web
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [287]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [289]:
volume = pd.DataFrame({ticker:data['Volume']
                    for ticker, data in all_data.items()})

In [290]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2017-05-16   36.794533  116.061653   65.164604   943.000000
2017-05-17   35.559155  113.984848   63.352619   919.619995
2017-05-18   36.101112  113.871536   63.568535   930.239990
2017-05-19   36.224178  114.777802   63.549770   934.010010
2017-05-22   36.444275  115.276245   64.263298   941.859985
...                ...         ...         ...          ...
2022-05-09  152.059998  134.440002  264.579987  2261.679932
2022-05-10  154.509995  129.130005  269.500000  2291.689941
2022-05-11  146.500000  130.750000  260.549988  2279.219971
2022-05-12  142.559998  132.899994  255.350006  2263.219971
2022-05-13  147.110001  133.600006  261.119995  2330.310059

[1259 rows x 4 columns]

In [291]:
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2017-05-16   80194000.0  5767330.0  34956000.0   969500
2017-05-17  203070800.0  5430309.0  30548800.0  2362100
2017-05-18  134272800.0  3424813.0  25201300.0  1596900
2017-05-19  107843200.0  5902578.0  26961100.0  1393000
2017-05-22   91865600.0  3453997.0  16237600.0  1120400
...                 ...        ...         ...      ...
2022-05-09  131577900.0  7647900.0  47726000.0  1726000
2022-05-10  115366700.0  8642400.0  39336400.0  1557900
2022-05-11  142689800.0  5301100.0  48975900.0  1825100
2022-05-12  182602000.0  5384800.0  51033800.0  2073200
2022-05-13  113787000.0  4195100.0  34893400.0  1486000

[1259 rows x 4 columns]

In [292]:
returns = price.pct_change()

In [293]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-05-09 -0.033189 -0.011616 -0.036945 -0.022272
2022-05-10  0.016112 -0.039497  0.018596  0.013269
2022-05-11 -0.051841  0.012545 -0.033210 -0.005441
2022-05-12 -0.026894  0.016444 -0.019958 -0.007020
2022-05-13  0.031916  0.005267  0.022596  0.029644

In [294]:
returns['MSFT'].corr(returns['IBM'])

0.47366035210588936

In [295]:
returns['MSFT'].cov(returns['IBM'])

0.00014655236268370099

In [296]:
returns.MSFT.corr(returns.IBM)

0.47366035210588936

In [297]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.427023  0.752112  0.676465
IBM   0.427023  1.000000  0.473660  0.450844
MSFT  0.752112  0.473660  1.000000  0.785916
GOOG  0.676465  0.450844  0.785916  1.000000

In [298]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000396  0.000144  0.000273  0.000242
IBM   0.000144  0.000287  0.000147  0.000137
MSFT  0.000273  0.000147  0.000334  0.000258
GOOG  0.000242  0.000137  0.000258  0.000324

In [299]:
returns.corrwith(returns.IBM)

AAPL    0.427023
IBM     1.000000
MSFT    0.473660
GOOG    0.450844
dtype: float64

In [300]:
returns.corrwith(volume)

AAPL   -0.084273
IBM    -0.100149
MSFT   -0.074719
GOOG   -0.099918
dtype: float64

In [301]:
# Unique Values, Value Counts, and Membership

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [302]:
uniques = obj.unique()

In [303]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [304]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [305]:
pd.value_counts(obj.values, sort=False)

b    2
a    3
d    1
c    3
dtype: int64

In [306]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [307]:
mask = obj.isin(['b', 'c'])

In [308]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [309]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [310]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [311]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [312]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [313]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
                    'Qu2': [2,3,1,2,3],
                    'Qu3': [1,5,2,4,4]})

In [314]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [315]:
result = data.apply(pd.value_counts).fillna(0)

In [316]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0